jenkins-pipeline-intitialization

diff --git a/catalogue-cd/Jenkinsfile b/catalogue-cd/Jenkinsfile
--- a/catalogue-cd/Jenkinsfile
+++ b/catalogue-cd/Jenkinsfile
@@ -21,45 +21,47 @@ pipeline {
     stages {
         stage('Deploy') {
             steps {
-                script {
-                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
-                        sh """
-                            aws eks update-kubeconfig --region $REGION --name "$PROJECT-${params.deploy_to}"
-                            kubectl get nodes
-                            kubectl apply -f 01-namespace.yaml
-                            sed -i "s/IMAGE_VERSION/${params.appVersion}/g" values-${params.deploy_to}.yaml
-                            #helm upgrade --install $COMPONENT -f values-${params.deploy_to}.yaml -n $PROJECT .
-                            kubectl apply -f application.yaml
-                        """
+                 dir('catalogue-ci') {
+                    script {
+                        withAWS(credentials: 'aws-creds', region: 'us-east-1') {
+                            sh """
+                                aws eks update-kubeconfig --region $REGION --name "$PROJECT-${params.deploy_to}"
+                                kubectl get nodes
+                                kubectl apply -f 01-namespace.yaml
+                                sed -i "s/IMAGE_VERSION/${params.appVersion}/g" values-${params.deploy_to}.yaml
+                                #helm upgrade --install $COMPONENT -f values-${params.deploy_to}.yaml -n $PROJECT .
+                                kubectl apply -f application.yaml
+                            """
+                        }
                     }
-                }
+                }    
             }
         }
 
  // checkinsg-status and if any failure of deployement then rollback to previous version 
         stage('Check Status'){
             steps{
-                script{
-                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
-                        def deploymentStatus = sh(returnStdout: true, script: "kubectl rollout status deployment/catalogue --timeout=30s -n $PROJECT || echo FAILED").trim()
-                        if (deploymentStatus.contains("successfully rolled out")) {
-                            echo "Deployment is success"
-                        } else {
-                            sh """
-                                helm rollback $COMPONENT -n $PROJECT
-                                sleep 20
-                            """
-                            def rollbackStatus = sh(returnStdout: true, script: "kubectl rollout status deployment/catalogue --timeout=30s -n $PROJECT || echo FAILED").trim()
-                            if (rollbackStatus.contains("successfully rolled out")) {
-                                error "Deployment is Failure, Rollback Success"
+                    script{
+                        withAWS(credentials: 'aws-creds', region: 'us-east-1') {
+                            def deploymentStatus = sh(returnStdout: true, script: "kubectl rollout status deployment/catalogue --timeout=30s -n $PROJECT || echo FAILED").trim()
+                            if (deploymentStatus.contains("successfully rolled out")) {
+                                echo "Deployment is success"
+                            } else {
+                                sh """
+                                    helm rollback $COMPONENT -n $PROJECT
+                                    sleep 20
+                                """
+                                def rollbackStatus = sh(returnStdout: true, script: "kubectl rollout status deployment/catalogue --timeout=30s -n $PROJECT || echo FAILED").trim()
+                                if (rollbackStatus.contains("successfully rolled out")) {
+                                    error "Deployment is Failure, Rollback Success"
+                                }
+                                else{
+                                    error "Deployment is Failure, Rollback Failure. Application is not running"
+                                }
                             }
-                            else{
-                                error "Deployment is Failure, Rollback Failure. Application is not running"
-                            }
-                        }
 
-                    }
-                }
+                        }
+                    }    
             }
         }
 
