jenkins-pipeline-intitialization

diff --git a/user-cd/Jenkinsfile b/user-cd/Jenkinsfile
--- a/user-cd/Jenkinsfile
+++ b/user-cd/Jenkinsfile
@@ -5,9 +5,9 @@ pipeline {
     environment { 
         appVersion = ''
         REGION = "us-east-1"
-        ACC_ID = "468236363049"
+        ACC_ID = "315069654700"
         PROJECT = "roboshop"
-        COMPONENT = "catalogue"
+        COMPONENT = "user"
     }
     options {
         timeout(time: 30, unit: 'MINUTES') 
@@ -19,6 +19,31 @@ pipeline {
     }
     // Build
     stages {
+        stage('Check Status'){
+            steps{
+                script{
+                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
+                        def deploymentStatus = sh(returnStdout: true, script: "kubectl rollout status deployment/user --timeout=30s -n $PROJECT || echo FAILED").trim()
+                        if (deploymentStatus.contains("successfully rolled out")) {
+                            echo "Deployment is success"
+                        } else {
+                            sh """
+                                helm rollback $COMPONENT -n $PROJECT
+                                sleep 20
+                            """
+                            def rollbackStatus = sh(returnStdout: true, script: "kubectl rollout status deployment/user --timeout=30s -n $PROJECT || echo FAILED").trim()
+                            if (rollbackStatus.contains("successfully rolled out")) {
+                                error "Deployment is Failure, Rollback Success"
+                            }
+                            else{
+                                error "Deployment is Failure, Rollback Failure. Application is not running"
+                            }
+                        }
+
+                    }
+                }
+            }
+        }
         stage('Deploy') {
             steps {
                 script {
@@ -28,36 +53,8 @@ pipeline {
                             kubectl get nodes
                             kubectl apply -f 01-namespace.yaml
                             sed -i "s/IMAGE_VERSION/${params.appVersion}/g" values-${params.deploy_to}.yaml
-                            #helm upgrade --install $COMPONENT -f values-${params.deploy_to}.yaml -n $PROJECT .
-                            kubectl apply -f application.yaml
+                            helm upgrade --install $COMPONENT -f values-${params.deploy_to}.yaml -n $PROJECT .
                         """
-                    }
-                }
-            }
-        }
-
- // checkinsg-status and if any failure of deployement then rollback to previous version 
-        stage('Check Status'){
-            steps{
-                script{
-                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
-                        def deploymentStatus = sh(returnStdout: true, script: "kubectl rollout status deployment/catalogue --timeout=30s -n $PROJECT || echo FAILED").trim()
-                        if (deploymentStatus.contains("successfully rolled out")) {
-                            echo "Deployment is success"
-                        } else {
-                            sh """
-                                helm rollback $COMPONENT -n $PROJECT
-                                sleep 20
-                            """
-                            def rollbackStatus = sh(returnStdout: true, script: "kubectl rollout status deployment/catalogue --timeout=30s -n $PROJECT || echo FAILED").trim()
-                            if (rollbackStatus.contains("successfully rolled out")) {
-                                error "Deployment is Failure, Rollback Success"
-                            }
-                            else{
-                                error "Deployment is Failure, Rollback Failure. Application is not running"
-                            }
-                        }
-
                     }
                 }
             }
